server:
 port: 8089

application:
 config:
  customer-url: http://localhost:8888/api/v1/customers
  payment-url: http://localhost:8222/api/v1/payments
  product-url: http://localhost:8222/api/v1/products
