build:
    version: "3.0.0"

customer:
    message: "Welcome to customer service"
    contactDetails:
        name: "sabbir"
        email: "sabbir@in.com"
        phone: "1234567890"
    onCallSupport:
        - 012587
        - 012588
