build:
    version: "3.0.0"

product:
    message: "Welcome to customer service"
    contactDetails:
        name: "sabbir"
        email: "sabbir@in.com"
        phone: "1234567890"
    onCallSupport:
        - 012587
        - 012588

application:
    config:
        customer-url: http://localhost:8222/api/v1/customers
        payment-url: http://localhost:8222/api/v1/payments
        product-url: http://localhost:8222/api/v1/products
